spring:
  profiles:
    active: dev

---

spring:
  profiles:
    include:
      - auth
      - datasource
      - aws

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB